plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.6'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.jws'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

repositories {
	mavenCentral()
}

dependencies {

	// Spring Boot
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'

	// Spring Security + OAuth2 Resource Server
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
	
	// MyBatis + PostgreSQL
	implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:4.0.1'
	runtimeOnly 'org.postgresql:postgresql'
	
	// OpenAPI (Swagger) UI
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.3'

	// Lambda + API Gateway 連携用
	implementation "com.amazonaws.serverless:aws-serverless-java-container-springboot4:3.0.2"

    /*
     * Springコンポーネント候補をコンパイル時に索引化する。
     * Lambdaの初期化時のコンポーネント探索を軽減する。
     */
    annotationProcessor 'org.springframework:spring-context-indexer'

    // Lambda Event型を使う場合
	implementation "com.amazonaws:aws-lambda-java-events:3.16.1"

    // AWS SDK v2
	implementation platform("software.amazon.awssdk:bom:2.41.32")
	implementation "software.amazon.awssdk:s3"
	implementation "software.amazon.awssdk:ssm"
	implementation "software.amazon.awssdk:secretsmanager"
	implementation "software.amazon.awssdk:sqs"

	// 開発用ツール
	developmentOnly 'org.springframework.boot:spring-boot-devtools'

	// テスト用
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-validation-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testImplementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter-test:4.0.1'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}

/*
 * Lambdaデプロイ用ZIP。
 *
 * ZIP構造:
 *
 * musicflows-lambda.zip
 * ├── com/jws/musicflows/...
 * ├── application.yml
 * └── lib/
 *     ├── spring-*.jar
 *     ├── aws-*.jar
 *     └── postgresql-*.jar
 */tasks.register('buildLambdaZip', Zip) {

	// Lambda デプロイ用 ZIP の作成は、コンパイル後に行う
    dependsOn tasks.named('classes')

    // ZIP のファイル名と出力先を指定する
    archiveFileName.set('musicflows-lambda.zip')
	// ZIP の出力先を build/distributions に指定する
    destinationDirectory.set(
        layout.buildDirectory.dir('distributions')
    )

    // ZIP のルートに、コンパイル済みクラスとリソースを配置する
    from sourceSets.main.output


   /*
     * 本番実行用の依存JARだけをlibへ配置する。
     *
     * productionRuntimeClasspathを使うことで、
     * developmentOnlyのDevToolsなどを除外する。
     */
    into('lib') {
        from(configurations.productionRuntimeClasspath) {
            
			// Tomcatの埋め込みJARを除外する
            exclude 'tomcat-embed-*.jar'
        }
    }

    
	
}