app:
  database:
    # DB接続情報そのものではなく、
    # Secrets ManagerのSecret名だけをSpring Bootへ渡す。
    secret-name: ${DB_SECRET_NAME}

    hikari:
      maximum-pool-size: 2
      minimum-idle: 0
      connection-timeout: 5000 
      idle-timeout: 30000 # 接続がアイドル状態のまま保持される最大時間（ミリ秒）

logging:
  level:
    root: INFO
    com.jws.musicflows: INFO